name: Install from Mirror Example
on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

env:
  SOURCE: mirror

jobs:
  latest-version:
    name: Latest version
    strategy:
      fail-fast: false
      matrix:
        os: [  "ubuntu-20.04" ]
        cache: [ true, false ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: redhat-actions/openshift-tools-installer@v1
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          skip_cache: ${{ matrix.cache }}
          oc: "latest" 

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x 
          oc version 
  known-version:
    name: Known version
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "windows-latest", "ubuntu-20.04" ]
        cache: [ true, false ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: redhat-actions/openshift-tools-installer@v1
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          skip_cache: ${{ matrix.cache }} 
          oc: "4" 

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x 
          oc version  || true
  latest-version-linux-macos:
    name: Latest version on linux & macOS
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "ubuntu-20.04" ]
        cache: [ true, false ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses:  redhat-actions/openshift-tools-installer@v1
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          skip_cache: ${{ matrix.cache }}
          operator-sdk: "latest"
          openshift-install: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          operator-sdk version
          openshift-install version
  known-version-linux-macos:
    name: Known version on linux & macOS
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "ubuntu-20.04" ]
        cache: [ true, false ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses:  redhat-actions/openshift-tools-installer@v1
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          skip_cache: ${{ matrix.cache }}
          operator-sdk: "4.7"
          openshift-install: "4.x"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          operator-sdk version
          openshift-install version
  known-version-linux:
    name: Known version on linux
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "ubuntu-20.04" ]
        cache: [ true, false ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses:  redhat-actions/openshift-tools-installer@v1
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          skip_cache: ${{ matrix.cache }}
          oc: "3" 

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        run: |
          set -x
          oc version
          opm version
  latest-version-linux-windows:
    name: Install CRC
    strategy:
      fail-fast: false
      matrix:
        # os: [ "windows-latest", "ubuntu-20.04" ]   # Skip install on windows https://github.com/redhat-actions/openshift-tools-installer/issues/50
        cache: [ true, false ]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses:  redhat-actions/openshift-tools-installer@v1
        id: install_clients
        with:
          source: ${{ env.SOURCE }}
          skip_cache: ${{ matrix.cache }}
          crc: "latest"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"

      - name: Run installed tools
        shell: bash
        run: |
          set -x